name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or whichever branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # or your preferred Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Vue project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          folder: dist # the folder containing the built assets
          branch: gh-pages # the branch where the deployed files will be pushed
          repository-name: ${{ github.repository }}
          single-commit: true
